# Generated by Django 5.0.3 on 2024-04-04 18:32

from django.db import migrations


def crear_objetos(apps, schema_editor):
    Product = apps.get_model("backend", "Product")
    product1 = Product(name="Empanada de pollo", restaurant="Eden")
    product1.save()
    product2 = Product(name="Empanada de verdura", restaurant="Eden")
    product2.save()
    product3 = Product(name="Empanada de carne", restaurant="Eden")
    product3.save()
    product4 = Product(name="Empanada de jamon y queso", restaurant="Eden")
    product4.save()
    product5 = Product(name="Empanada de humita", restaurant="Eden")
    product5.save()


def eliminar_objetos(apps, schema_editor):
    Product = apps.get_model("backend", "Product")
    Product.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user'),
    ]

    operations = [
        migrations.RunPython(crear_objetos, eliminar_objetos),
    ]
