# Generated by Django 5.0.3 on 2024-05-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_restaurant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
